apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "<base64-encoded-docker-config-json>" # use `kubectl create secret docker-registry` to generate

---
# Usage in a pod/deployment YAML:
# imagePullSecrets:
# - name: regcred
