apiVersion: v1
kind: Pod
metadata:
  name: runasnonroot-demo
spec:
  containers:
  - name: app
    image: nginx:1.21
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    ports:
    - containerPort: 80
  restartPolicy: Always
